### ISSUE TITLE
请问mitie支持python3.6吗？我安装的时候总出现这个问题

### ISSUE THREAD

**Issue by liuyue94** [zqhZY/rasa_chatbot#12]
C:\Users\user>pip3.6 install git+https://github.com/mit-nlp/MITIE.git
Collecting git+https://github.com/mit-nlp/MITIE.git
  Cloning https://github.com/mit-nlp/MITIE.git to c:\users\user\appdata\local\te
mp\pip-cn8fkq0n-build
Installing collected packages: mitie
  Running setup.py install for mitie ... error
Exception:
Traceback (most recent call last):
  File "d:\python3.6\lib\site-packages\pip\compat\__init__.py", line 73, in cons
ole_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 24: invalid
 continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\python3.6\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "d:\python3.6\lib\site-packages\pip\commands\install.py", line 342, in ru
n
    prefix=options.prefix_path,
  File "d:\python3.6\lib\site-packages\pip\req\req_set.py", line 784, in install

    **kwargs
  File "d:\python3.6\lib\site-packages\pip\req\req_install.py", line 878, in ins
tall
    spinner=spinner,
  File "d:\python3.6\lib\site-packages\pip\utils\__init__.py", line 676, in call
_subprocess
    line = console_to_str(proc.stdout.readline())
  File "d:\python3.6\lib\site-packages\pip\compat\__init__.py", line 75, in cons
ole_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 24: invalid
 continuation byte

**Comment by zqhZY** [comment]
Ubuntu 14下，是没问题的，win环境没有试过
└┤ pip install git+https://github.com/mit-nlp/MITIE.git
Collecting git+https://github.com/mit-nlp/MITIE.git
  Cloning https://github.com/mit-nlp/MITIE.git to /tmp/pip-mqv0erkx-build
  Requirement already satisfied (use --upgrade to upgrade): mitie==0.2.0 from git+https://github.com/mit-nlp/MITIE.git in /usr/local/lib/python3.6/site-packages

└┤ pip -V
pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)

**Comment by liuyue94** [comment]
收到，谢谢，我再去探索一下
