### ISSUE TITLE
训练rasa nlu模型出现错误

### ISSUE THREAD

**Issue by liuyue94** [zqhZY/rasa_chatbot#13]
D:\pycharm\pycharmproject\rasa_chatbot_v1>python bot.py train-nlu
 No Jieba User Dictionary found.
D:\python3.6\lib\site-packages\sklearn\base.py:311: UserWarning: Trying to unpickle estimator LabelEncoder from version 0.18.1 when using v
ersion 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
D:\python3.6\lib\site-packages\sklearn\base.py:311: UserWarning: Trying to unpickle estimator SVC from version 0.18.1 when using version 0.
19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
D:\python3.6\lib\site-packages\sklearn\base.py:311: UserWarning: Trying to unpickle estimator GridSearchCV from version 0.18.1 when using v
ersion 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Traceback (most recent call last):
  File "bot.py", line 160, in <module>
    train_nlu()
  File "bot.py", line 107, in train_nlu
    from rasa_nlu.converters import load_data
ModuleNotFoundError: No module named 'rasa_nlu.converters'

一个应该是说 No Jieba User Dictionary found.，另一个是ModuleNotFoundError: No module named 'rasa_nlu.converters'，我安装的是中文版的rasa nlu 也安装了结巴分词，不知道为啥出现这个问题

**Comment by zqhZY** [comment]
第一个应是警告，不会影响结果，第二个有可能是rasa_nlu版本的问题，或者是windows下的问题，可以尝试linux系统

**Comment by liuyue94** [comment]
谢谢啦

**Comment by xiaolong2009** [comment]
File "bot.py", line 120, in <module>
    interpreter=RasaNLUInterpreter("models/ivr/demo"),
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_core/interpreter.py", line 219, in __init__
    self._load_interpreter()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_core/interpreter.py", line 238, in _load_interpreter
    os.environ))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_nlu/model.py", line 230, in load
    skip_valdation)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_nlu/model.py", line 253, in create
    components.validate_requirements(model_metadata.pipeline)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_nlu/components.py", line 56, in validate_requirements
    component_class = registry.get_component_class(component_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_nlu/registry.py", line 136, in get_component_class
    "in a module.".format(component_name))
Exception: Failed to find component class for 'rasa_nlu.tokenizers.jieba_tokenizer.JiebaTokenizer'. Unknown component name. Check your configured pipeline and make sure the mentioned component is not misspelled. If you are creating your own component, make sure it is either listed as part of the `component_classes` in `rasa_nlu.registry.py` or is a proper name of a class in a module.
这个问题有人遇到吗？是不是和rasa-nlu 版本有关系，我的版本是0.11.5

**Comment by zqhZY** [comment]
感觉还是没有安装rasa nlu chi 到库里，如果rasa nlu chi 目录下可以运行的话，试试在目录下运行python setup.py install




| |
zqingheng
邮箱：zqingheng@163.com
|

签名由 网易邮箱大师 定制

在2018年04月27日 15:34，XIAOLONG 写道：

File "bot.py", line 120, in
interpreter=RasaNLUInterpreter("models/ivr/demo"),
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_core/interpreter.py", line 219, in init
self._load_interpreter()
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_core/interpreter.py", line 238, in _load_interpreter
os.environ))
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_nlu/model.py", line 230, in load
skip_valdation)
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_nlu/model.py", line 253, in create
components.validate_requirements(model_metadata.pipeline)
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_nlu/components.py", line 56, in validate_requirements
component_class = registry.get_component_class(component_name)
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_nlu/registry.py", line 136, in get_component_class
"in a module.".format(component_name))
Exception: Failed to find component class for 'rasa_nlu.tokenizers.jieba_tokenizer.JiebaTokenizer'. Unknown component name. Check your configured pipeline and make sure the mentioned component is not misspelled. If you are creating your own component, make sure it is either listed as part of the component_classes in rasa_nlu.registry.py or is a proper name of a class in a module.
这个问题有人遇到吗？是不是和rasa-nlu 版本有关系，我的版本是0.11.5
