### ISSUE TITLE
python bot.py online_train   eorror

### ISSUE THREAD

**Issue by binux1987** [zqhZY/rasa_chatbot#15]
Hello, when I exec like this command "python bot.py online_train". the error as bellow, could you help me check it? thanks a lot

Traceback (most recent call last):
  File "bot.py", line 120, in <module>
    interpreter=RasaNLUInterpreter("models/ivr/demo"),
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/interpreter.py", line 219, in __init__
    self._load_interpreter()
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/interpreter.py", line 234, in _load_interpreter
    from rasa_nlu.config import RasaNLUConfig
ImportError: cannot import name 'RasaNLUConfig'

**Comment by zqhZY** [comment]
是否正确安装了Rasa nul Chi，如果正确安装，有可能是软件版本的问题

**Comment by SuixueWang** [comment]
我也遇到同样问题了，请问下安装完Rasa nul Chi后是否固定了ras_nlu的版本？如果更新了版本，又不是Rasa nul Chi的了吧？有点矛盾，如何解决这个bug呢？谢谢！

**Comment by Liangzhu520** [comment]
Traceback (most recent call last):
  File "bot.py", line 13, in <module>
    from rasa_core.channels.console import ConsoleInputChannel
ImportError: cannot import name 'ConsoleInputChannel'
